# Generated by Django 3.2.6 on 2021-08-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa_texto', models.CharField(max_length=100)),
                ('descricao_texto', models.CharField(max_length=300)),
                ('importancia', models.IntegerField()),
            ],
        ),
    ]
